/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author aser
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    //getters para acceder a los botones desde el controlador escuchando
    public JButton getBtnIngresarCrear() {
        return btnIngresarCrear;
    }

    public JButton getBtnVisualizarInforme1() {
        return btnVisualizarInforme1;
    }

    public JButton getBtnVisualizarMayorEdad() {
        return btnVisualizarMayorEdad;
    }

    public JButton getBtnVisualizarMujeres5() {
        return btnVisualizarMujeres5;
    }
    
    //getters para mandar todos los componentes de la vista al controlador

    public JComboBox<String> getComboIngresarGrado() {
        return comboIngresarGrado;
    }

    public JComboBox<String> getComboIngresarSexo() {
        return comboIngresarSexo;
    }

    public JTextField getInputIngresarEdad() {
        return inputIngresarEdad;
    }

    public JTextField getInputIngresarId() {
        return inputIngresarId;
    }

    public JTextField getInputIngresarNombreAcudiente() {
        return inputIngresarNombreAcudiente;
    }

    public JTextField getInputIngresarNombreEstudiante() {
        return inputIngresarNombreEstudiante;
    }

    public JTextField getInputIngresarTelefono() {
        return inputIngresarTelefono;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelIngresar = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        inputIngresarId = new javax.swing.JTextField();
        lbl7 = new javax.swing.JLabel();
        inputIngresarNombreEstudiante = new javax.swing.JTextField();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        inputIngresarEdad = new javax.swing.JTextField();
        lbl11 = new javax.swing.JLabel();
        inputIngresarNombreAcudiente = new javax.swing.JTextField();
        comboIngresarSexo = new javax.swing.JComboBox<>();
        comboIngresarGrado = new javax.swing.JComboBox<>();
        lbl12 = new javax.swing.JLabel();
        inputIngresarTelefono = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnIngresarCrear = new javax.swing.JButton();
        panelVisualizar = new javax.swing.JPanel();
        lbl13 = new javax.swing.JLabel();
        btnVisualizarMayorEdad = new javax.swing.JButton();
        lbl14 = new javax.swing.JLabel();
        btnVisualizarMujeres5 = new javax.swing.JButton();
        lbl15 = new javax.swing.JLabel();
        btnVisualizarInforme1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl1.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl1.setText("ID del estudiante:");

        inputIngresarId.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N

        lbl7.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl7.setText("Nombre del estudiante:");

        inputIngresarNombreEstudiante.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N

        lbl8.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl8.setText("Sexo del estudiante:");

        lbl9.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl9.setText("Grado del estudiante:");

        lbl10.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl10.setText("Edad del estudiante:");

        inputIngresarEdad.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N

        lbl11.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl11.setText("Nombre del acudiente:");

        inputIngresarNombreAcudiente.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N

        comboIngresarSexo.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N
        comboIngresarSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer" }));

        comboIngresarGrado.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N
        comboIngresarGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        lbl12.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl12.setText("Telefono del acudiente:");

        inputIngresarTelefono.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N

        btnIngresarCrear.setText("Crear estudiante");

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarLayout.createSequentialGroup()
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(panelIngresarLayout.createSequentialGroup()
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelIngresarLayout.createSequentialGroup()
                                        .addComponent(lbl1)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputIngresarId))
                                    .addGroup(panelIngresarLayout.createSequentialGroup()
                                        .addComponent(lbl7)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputIngresarNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelIngresarLayout.createSequentialGroup()
                                        .addComponent(lbl8)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboIngresarSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelIngresarLayout.createSequentialGroup()
                                        .addComponent(lbl9)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboIngresarGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelIngresarLayout.createSequentialGroup()
                                        .addComponent(lbl10)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputIngresarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarLayout.createSequentialGroup()
                                        .addComponent(lbl11)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputIngresarNombreAcudiente))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarLayout.createSequentialGroup()
                                        .addComponent(lbl12)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputIngresarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnIngresarCrear)))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1)
                    .addComponent(inputIngresarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl7)
                    .addComponent(inputIngresarNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(comboIngresarSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl9)
                    .addComponent(comboIngresarGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl10)
                    .addComponent(inputIngresarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl11)
                    .addComponent(inputIngresarNombreAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl12)
                    .addComponent(inputIngresarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresarCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar Estudiantes", panelIngresar);

        lbl13.setText("(1) Estudiantes de mayor edad 1° y 5°, nombre y sexo");

        btnVisualizarMayorEdad.setText("Mostrar");

        lbl14.setText("(2) Informe de Estudiantes mujeres 5°, cantidad y edad");

        btnVisualizarMujeres5.setText("Mostrar");

        lbl15.setText("(3) Infomre de estudiantes 1°");

        btnVisualizarInforme1.setText("Mostrar");

        javax.swing.GroupLayout panelVisualizarLayout = new javax.swing.GroupLayout(panelVisualizar);
        panelVisualizar.setLayout(panelVisualizarLayout);
        panelVisualizarLayout.setHorizontalGroup(
            panelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisualizarLayout.createSequentialGroup()
                .addGroup(panelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVisualizarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl13))
                    .addGroup(panelVisualizarLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnVisualizarMayorEdad))
                    .addGroup(panelVisualizarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl14))
                    .addGroup(panelVisualizarLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnVisualizarMujeres5))
                    .addGroup(panelVisualizarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl15))
                    .addGroup(panelVisualizarLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnVisualizarInforme1)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panelVisualizarLayout.setVerticalGroup(
            panelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizarMayorEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizarMujeres5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizarInforme1)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visualizar Estudiantes", panelVisualizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarCrear;
    private javax.swing.JButton btnVisualizarInforme1;
    private javax.swing.JButton btnVisualizarMayorEdad;
    private javax.swing.JButton btnVisualizarMujeres5;
    private javax.swing.JComboBox<String> comboIngresarGrado;
    private javax.swing.JComboBox<String> comboIngresarSexo;
    private javax.swing.JTextField inputIngresarEdad;
    private javax.swing.JTextField inputIngresarId;
    private javax.swing.JTextField inputIngresarNombreAcudiente;
    private javax.swing.JTextField inputIngresarNombreEstudiante;
    private javax.swing.JTextField inputIngresarTelefono;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JPanel panelIngresar;
    private javax.swing.JPanel panelVisualizar;
    // End of variables declaration//GEN-END:variables
}
